Client/Models/Notifications/NotificationViewModel.cs
using System;

namespace Client.Models.Notifications
{
    public class NotificationViewModel
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Content { get; set; }
        public bool IsDismissed { get; set; }
        public DateTime Date { get; set; }
    }
}

Client/Controllers/NotificationsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using Client.BLL.DTO;
using Client.BLL.Interfaces;
using Client.Models.Notifications;

namespace Client.Controllers
{
    [Authorize]
    public class NotificationsController : BaseController
    {
        public NotificationsController(INotificationService notificationService) : base(notificationService)
        {
        }

        public ActionResult Index()
        {
            var notificationsDto = NotificationService.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<NotificationDto, NotificationViewModel>())
                .CreateMapper();
            var notifications = mapper.Map<IEnumerable<NotificationDto>, List<NotificationViewModel>>(notificationsDto)
                .Select(i => i).Where(i => i.IsDismissed == false);
            ViewBag.NotificationCount = notifications.Count();
            return View(notifications);
        }

        [HttpPost]
        public ActionResult Dismiss(int? id)
        {
            NotificationService.Dismiss(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DismissAll()
        {
            NotificationService.DismissAll();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [HttpPost]
        public Task Receive(NotificationDto notification)
        {
            NotificationService.Add(notification);
            return Task.CompletedTask;
        }
    }
}

Client/Views/Notifications/Index.cshtml
@model IEnumerable<Client.Models.Notifications.NotificationViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" align="center">
    <h2>Notifications</h2>
    @if (Model.Any())
    {
        <div class="col-lg-12">
            @foreach (var notification in Model)
            {
                @Html.Partial("NotificationPartial", notification)
            }
            @using (Html.BeginForm("DismissAll", "Notifications", FormMethod.Post))
            {
                <button type="submit" class="btn btn-warning">Dismiss all</button>
            }
        </div>
    }
    else
    {
        <div class="alert alert-success" role="alert">
            <h4>You do not have any notification.</h4>
        </div>
    }
</div>

Client/Views/Notifications/NotificationPartial.cshtml
@model Client.Models.Notifications.NotificationViewModel
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title">Notification from <strong>@Model.UserName</strong> at <strong>@Model.Date</strong></h3>
    </div>
    <div class="panel-body">
        <h2 class="">@Model.Content</h2>
        @using (Html.BeginForm("Dismiss", "Notifications", FormMethod.Post))
        {
            <input type="hidden" value="@Model.Id" name="Id"/>
            <button type="submit" class="btn btn-success">Dismiss</button>
        }
    </div>
</div>