Client/Models/Tickets/TicketViewModel.cs
using System;

namespace Client.Models.Tickets
{
    public class TicketViewModel
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public DateTime DepartureDate { get; set; }
        public DateTime ArrivalDate { get; set; }
        public string ServiceClass { get; set; }
    }
}

Client/Controllers/TicketController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Client.BLL.DTO;
using Client.BLL.Interfaces;
using Client.Models.Tickets;

namespace Client.Controllers
{
    [Authorize]
    public class TicketController : BaseController
    {
        private readonly ITicketService ticketService;

        public TicketController(INotificationService notificationService, ITicketService ticketService) : base(notificationService)
        {
            this.ticketService = ticketService;
        }

        public ActionResult Index()
        {
            var count = NotificationService.GetAll().Select(i => i).Count(i => i.IsDismissed == false);
            ViewBag.NotificationCount = count;
            var ticketsDto = ticketService.GetAll();
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<TicketDto, TicketViewModel>())
                .CreateMapper();
            var tickets = mapper.Map<IEnumerable<TicketDto>, List<TicketViewModel>>(ticketsDto);
            return View(tickets);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var count = NotificationService.GetAll().Select(i => i).Count(i => i.IsDismissed == false);
            ViewBag.NotificationCount = count;
            return View();
        }

        [HttpPost]
        public ActionResult Create(TicketViewModel ticketViewModel)
        {
            ticketService.Create(new TicketDto
            {
                ArrivalDate = ticketViewModel.ArrivalDate,
                DepartureDate = ticketViewModel.DepartureDate,
                From = ticketViewModel.From,
                ServiceClass = ticketViewModel.ServiceClass,
                To = ticketViewModel.To
            });
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult TicketsForClient(string serviceClass)
        {
            var count = NotificationService.GetAll().Select(i => i).Count(i => i.IsDismissed == false);
            ViewBag.NotificationCount = count;
            var ticketsDto = ticketService.GetAllByClass(serviceClass);
            var mapper = new MapperConfiguration(cfg => cfg.CreateMap<TicketDto, TicketViewModel>())
                .CreateMapper();
            var tickets = mapper.Map<IEnumerable<TicketDto>, List<TicketViewModel>>(ticketsDto);
            return View("Index", tickets);
        }
    }
}

Client/Views/Ticket/Create.cshtml
@model Client.Models.Tickets.TicketViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add ticket</h2>
<form class="form-horizontal" action="Create" method="post">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)
    <div class="form-group">
        <label class="control-label col-sm-2" for="from">From:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="From" id="from" placeholder="Enter the start point">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="to">To:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="To" id="to" placeholder="Enter the end point">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="departure">Depart at:</label>
        <div class="col-sm-10">
            <input type="datetime" class="form-control" name="DepartureDate" id="departure" placeholder="Departure date">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="arrival">Arrives at:</label>
        <div class="col-sm-10">
            <input type="datetime" class="form-control" name="ArrivalDate" id="arrival" placeholder="Arrival date">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="class">Service class:</label>
        <div class="col-sm-10">
            <select class="form-control" name="ServiceClass" id="class">
                <option>Business</option>
                <option>Economy</option>
                <option>First</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Add</button>
        </div>
    </div>
</form>

Client/Views/Ticket/Index.cshtml
@model IEnumerable<Client.Models.Tickets.TicketViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row" align="center">
    <h2>Available Tickets</h2>
    @if (Model.Any())
    {
        foreach (var ticket in Model)
        {
            @Html.Partial("TicketPartial", ticket)
        }
    }
    else
    {
        <div class="alert alert-warning" role="alert">
            <h4>Tickets are not available.</h4>
        </div>
    }

    @using (Html.BeginForm("Create", "Ticket", FormMethod.Get))
    {
        <button type="submit" class="btn btn-primary">Add new ticket</button>
    }
</div>

Client/Views/Ticket/TicketPartial.cshtml
@model Client.Models.Tickets.TicketViewModel
<div class="panel panel-info">
    <div class="panel-body">
        <p><text>From: <strong>@Model.From</strong></text></p>
        <p><text>To: <strong>@Model.To</strong></text></p>
        <p><text>Departure date: <strong>@Model.DepartureDate</strong></text></p>
        <p><text>Arrival date: <strong>@Model.ArrivalDate</strong></text></p>
        <p><text>Service class: <strong>@Model.ServiceClass</strong></text></p>
    </div>
</div>